# Quick Start
#
# 1. Run `xhost +local:docker && docker compose -f compose.simulation.yaml up` on the laptop
#    (optionally you can chang `gpu-config` -> `cpu config`).
# 2. Open a shell inside a docker container `docker compose -f compose.simulation.yaml exec -it robot bash`
# 3. Run `ros2 run teleop_twist_keyboard teleop_twist_keyboard` inside the container

x-gpu-config: &gpu-config
  runtime: nvidia
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config: &cpu-config
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}

services:
  robot:
    # image: goldjunge91/robot-gazebo:humble
    build:
      context: ..
      dockerfile: docker/Dockerfile.simulation
    network_mode: host
    ipc: host
    <<: [ *gpu-config ]
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch robot_gazebo simulation.launch.py
        robot_model:=${ROBOT_MODEL_NAME:-"Error: Specify robot model"}
