teleop_twist_joy_node:
  ros__parameters:
    # Xbox One Elite 2 Controller Button Mapping
    # Buttons: A=0, B=1, X=2, Y=3, LB=4, RB=5, Back=6, Start=7
    # Axes: LeftStickX=0, LeftStickY=1, RightStickX=2, RightStickY=3, LT=4, RT=5
    
    # Enable button (disabled - no button needed)
    enable_button: -1  # -1 = always enabled, no button needed
    enable_turbo_button: 5  # RB for turbo mode
    
    # Axis mapping for mecanum drive
    axis_linear:
      x: 1  # Left stick Y-axis (forward/backward)
      y: 0  # Left stick X-axis (strafe left/right)
      z: -1 # Not used
    
    axis_angular:
      yaw: 2    # Right stick X-axis (rotate)
      pitch: -1 # Not used
      roll: -1  # Not used
    
    # Speed scaling (normal mode)
    scale_linear:
      x: 0.8   # Forward/backward speed (erhöht)
      y: 0.8   # Strafe speed (erhöht)
      z: 0.0
    
    scale_angular:
      yaw: 1.5   # Rotation speed (erhöht)
      pitch: 0.0
      roll: 0.0
    
    # Speed scaling (turbo mode - when RB is pressed)
    scale_linear_turbo:
      x: 1.0   # Faster forward/backward
      y: 1.0   # Faster strafe
      z: 0.0
    
    scale_angular_turbo:
      yaw: 1.5   # Faster rotation
      pitch: 0.0
      roll: 0.0
    
    # Other settings
    require_enable_button: false  # No button needed to drive
    publish_stamped_twist: false
    inverted_reverse: false
